[package]
name = "ulnk"
version = "0.1.0"
authors = ["Dominik Winecki <dominikwinecki@gmail.com>"]

[dependencies]
config = "*"
log = "*"
env_logger = "*"
postgres  = "*"
futures = "0.1.14"
hyper = "0.11"
